{
 "title": "Mikrotik monitoring",
 "description": "Mikrotik snmp monitoring",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "Job",
    "query": "label_values(ifHCInOctets,  job)"
   },
   {
    "name": "instance",
    "query": "label_values(ifHCInOctets,  instance)"
   },
   {
    "name": "index",
    "query": "label_values(ifHighSpeed{instance='$instance'},ifIndex)"
   },
   {
    "name": "Interface",
    "query": "query_result(sort(ifIndex{ifName=~'^(ether).+',instance='$instance'}) or sort(ifIndex{ifName=~'^(sfp|wlan).+',instance='$instance'}) or sort(ifIndex{ifName=~'^bridge.+',instance='$instance'}) or  sort(ifIndex{ifName!~'^(ether|bridge).+',instance='$instance'}) )"
   },
   {
    "name": "desc",
    "query": "query_result(ifHCInOctets{ifName=\"$Interface\",instance=\"$instance\"})"
   },
   {
    "name": "queuesimple_name",
    "query": "query_result((mtxrQueueSimplePacketsIn * on (mtxrQueueSimpleIndex) group_left(mtxrQueueSimpleName) mtxrQueueSimpleName{instance='$instance',}))"
   }
  ]
 },
 "panels": [
  {
   "title": "uptime",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "sysUpTime{instance='$instance'}/100"
    }
   ]
  },
  {
   "title": "Load CPU",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "hrProcessorLoad{instance='$instance'}",
     "legendFormat": "Load CPU"
    }
   ]
  },
  {
   "title": "Load RAM",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(hrStorageUsed{hrStorageIndex='65536',instance='$instance'} * 100 )/(hrStorageSize{hrStorageIndex='65536',instance='$instance'})"
    }
   ]
  },
  {
   "title": "Load system disk",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(hrStorageUsed{hrStorageIndex='131072',instance='$instance'} * 100 )/(hrStorageSize{hrStorageIndex='131072',instance='$instance'})"
    }
   ]
  },
  {
   "title": "Queue Simple",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queue Simple - \"$queuesimple_name\"",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
     "repeat": "queuesimple_name",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "(irate(mtxrQueueSimpleBytesIn[30s])*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{mtxrQueueSimpleName='$queuesimple_name',instance='$instance'}) *8 ",
       "legendFormat": "In"
      },
      {
       "expr": "(irate(mtxrQueueSimpleBytesOut[30s])*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{mtxrQueueSimpleName='$queuesimple_name',instance='$instance'})*8",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "Queue Simple - \"$queuesimple_name\"",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "(irate(mtxrQueueSimpleBytesIn[30s])*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{mtxrQueueSimpleName='$queuesimple_name',instance='$instance'}) *8 ",
       "legendFormat": "In"
      },
      {
       "expr": "(irate(mtxrQueueSimpleBytesOut[30s])*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{mtxrQueueSimpleName='$queuesimple_name',instance='$instance'})*8",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "Queue Simple - \"$queuesimple_name\"",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "(irate(mtxrQueueSimpleBytesIn[30s])*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{mtxrQueueSimpleName='$queuesimple_name',instance='$instance'}) *8 ",
       "legendFormat": "In"
      },
      {
       "expr": "(irate(mtxrQueueSimpleBytesOut[30s])*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{mtxrQueueSimpleName='$queuesimple_name',instance='$instance'})*8",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "Queue Simple - \"$queuesimple_name\"",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "(irate(mtxrQueueSimpleBytesIn[30s])*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{mtxrQueueSimpleName='$queuesimple_name',instance='$instance'}) *8 ",
       "legendFormat": "In"
      },
      {
       "expr": "(irate(mtxrQueueSimpleBytesOut[30s])*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{mtxrQueueSimpleName='$queuesimple_name',instance='$instance'})*8",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "Queue Simple - \"$queuesimple_name\"",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "(irate(mtxrQueueSimpleBytesIn[30s])*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{mtxrQueueSimpleName='$queuesimple_name',instance='$instance'}) *8 ",
       "legendFormat": "In"
      },
      {
       "expr": "(irate(mtxrQueueSimpleBytesOut[30s])*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{mtxrQueueSimpleName='$queuesimple_name',instance='$instance'})*8",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "Queue Simple - \"$queuesimple_name\"",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "(irate(mtxrQueueSimpleBytesIn[30s])*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{mtxrQueueSimpleName='$queuesimple_name',instance='$instance'}) *8 ",
       "legendFormat": "In"
      },
      {
       "expr": "(irate(mtxrQueueSimpleBytesOut[30s])*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{mtxrQueueSimpleName='$queuesimple_name',instance='$instance'})*8",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "Queue Simple - \"$queuesimple_name\"",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "(irate(mtxrQueueSimpleBytesIn[30s])*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{mtxrQueueSimpleName='$queuesimple_name',instance='$instance'}) *8 ",
       "legendFormat": "In"
      },
      {
       "expr": "(irate(mtxrQueueSimpleBytesOut[30s])*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{mtxrQueueSimpleName='$queuesimple_name',instance='$instance'})*8",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "Queue Simple - \"$queuesimple_name\"",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "(irate(mtxrQueueSimpleBytesIn[30s])*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{mtxrQueueSimpleName='$queuesimple_name',instance='$instance'}) *8 ",
       "legendFormat": "In"
      },
      {
       "expr": "(irate(mtxrQueueSimpleBytesOut[30s])*on(mtxrQueueSimpleIndex)group_left(mtxrQueueSimpleName)mtxrQueueSimpleName{mtxrQueueSimpleName='$queuesimple_name',instance='$instance'})*8",
       "legendFormat": "Out"
      }
     ]
    }
   ]
  },
  { "title": "All interface", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "In / Out - \"$Interface\"",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "repeat": "Interface",
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{job='snmp',ifName=~'$Interface',instance='$instance'}[20s])*8",
     "legendFormat": "In"
    },
    {
     "expr": "irate(ifHCOutOctets{job='snmp',ifName=~'$Interface',instance='$instance'}[20s])*8",
     "legendFormat": "Out"
    }
   ]
  }
 ]
}