global:
  scrape_interval: '10s'

scrape_configs:
  - job_name: 'vmagent'
    static_configs:
      - targets: ['vmagent:8429']

  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['victoriametrics:8428']

  - job_name: 'traefik'
    scrape_interval: 1s
    scrape_timeout: 3s
    static_configs:
      - targets:
        - '172.16.1.1:8082'

  - job_name: 'gitlab_runner'
    scrape_interval: 1s
    scrape_timeout: 3s
    static_configs:
      - targets:
        - '172.16.1.13:9252'

  - job_name: 'snmp'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets:
        - 192.168.0.1
        - 192.168.0.2
    metrics_path: /snmp
    params:
      module: [mikrotik]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp:9116
